[build]
  publish = "."
  command = "# no build command needed"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "functions"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  publish = "."
  jwtRolePath = "app_metadata.authorization.roles"
  autoLaunch = true

[identity]
  enable = true 