[build]
  command = "npm install"
  publish = "."
  functions = "functions"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[functions."get-game-days"]
  included_files = ["functions/supabase-config.js"]
  environment = { SUPABASE_URL = "https://jfimhmaasapqfsjthglq.supabase.co", SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmY2RkY2RkY2RkY2RkY2RkY2RkIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTk5OTk5OTksImV4cCI6MjAxNTU3NTk5OX0.YOUR_JWT_TOKEN" }

[functions."get-registrations"]
  included_files = ["functions/supabase-config.js"]
  environment = { SUPABASE_URL = "https://jfimhmaasapqfsjthglq.supabase.co", SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmY2RkY2RkY2RkY2RkY2RkY2RkIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTk5OTk5OTksImV4cCI6MjAxNTU3NTk5OX0.YOUR_JWT_TOKEN" }

[functions."toggle-registration"]
  included_files = ["functions/supabase-config.js"]
  environment = { SUPABASE_URL = "https://jfimhmaasapqfsjthglq.supabase.co", SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmY2RkY2RkY2RkY2RkY2RkY2RkIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTk5OTk5OTksImV4cCI6MjAxNTU3NTk5OX0.YOUR_JWT_TOKEN" }

[dev]
  framework = "#custom"
  command = "node server.js"
  targetPort = 3000
  port = 3001
  publish = "."
  jwtRolePath = "app_metadata.authorization.roles"
  autoLaunch = true

[identity]
  enable = true 